name: Continuous Deployment

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-security-and-push:
    name: Build, Scan and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      - name: Build Docker image locally (for scanning)
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: .
          load: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test-scan

      - name: Run Trivy vulnerability scanner
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy image \
            --severity CRITICAL,HIGH \
            --exit-code 1 \
            --format sarif \
            --output trivy-results.sarif \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test-scan

      - name: Log in to the Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=sha,format=short

      - name: Push Docker image to GHCR
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Trigger Render Deployment
    needs: docker-security-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Notificar o servidor para iniciar o Deploy
        run: |
          if [ -z "${{ secrets.DEPLOY_HOOK_URL }}" ]; then
            echo "A secret DEPLOY_HOOK_URL não foi configurada."
            exit 1
          fi
          curl -X POST "${{ secrets.DEPLOY_HOOK_URL }}"

      - name: Sucesso
        run: echo "🚀 Deploy disparado com sucesso para a produção!"
