name: Continuous Deployment

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-security-and-push:
    name: Build, Scan and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.1.7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9746f4b2330b666a4220377402636f # v3.3.0

      - name: Build Docker image locally (for scanning)
        uses: docker/build-push-action@afed92cc177423e89547d079d8f3195204481008 # v5.3.0
        with:
          context: .
          load: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test-scan

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@5108619623838634517bbf08365f241a780e159c # v0.28.0
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test-scan'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      - name: Log in to the Container Registry
        uses: docker/login-action@9780f0c4423c1054093951f224a313d42bc02f52 # v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f787526f1e2d8f8d19755c6f74efa # v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=sha,format=short

      - name: Push Docker image to GHCR
        uses: docker/build-push-action@afed92cc177423e89547d079d8f3195204481008 # v5.3.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Trigger Render Deployment
    needs: docker-security-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Notificar o servidor para iniciar o Deploy
        run: |
          if [ -z "${{ secrets.DEPLOY_HOOK_URL }}" ]; then
            echo "A secret DEPLOY_HOOK_URL não foi configurada."
            exit 1
          fi
          curl -X POST "${{ secrets.DEPLOY_HOOK_URL }}"

      - name: Sucesso
        run: echo "🚀 Deploy disparado com sucesso para a produção!"
